# Generated by Django 2.2 on 2019-04-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190409_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.IntegerField(choices=[(3, 'FirstPersonShooter'), (1, 'Sci-Fi'), (0, 'Nieznany'), (4, 'Indie'), (2, 'Horrot')], default=0)),
            ],
        ),
    ]
