# Generated by Django 2.2 on 2019-04-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190409_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(0, 'Nieznany'), (2, 'Horrot'), (4, 'Indie'), (3, 'FirstPersonShooter'), (1, 'Sci-Fi')], default=0),
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=128)),
                ('kraj', models.CharField(max_length=128)),
                ('gry', models.ManyToManyField(to='main.Games')),
            ],
        ),
    ]
