# Generated by Django 2.2 on 2019-04-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190409_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='platform',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(2, 'Horrot'), (3, 'FirstPersonShooter'), (4, 'Indie'), (0, 'Nieznany'), (1, 'Sci-Fi')], default=0),
        ),
    ]
