# Generated by Django 2.2 on 2019-04-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190409_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='info',
        ),
        migrations.AddField(
            model_name='games',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='games',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='okladka'),
        ),
        migrations.DeleteModel(
            name='ExtraInfo',
        ),
    ]
