# Generated by Django 2.2 on 2019-04-10 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190410_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.IntegerField(choices=[(3, 'FirstPersonShooter'), (2, 'Horrot'), (4, 'Indie'), (0, 'Nieznany'), (1, 'Sci-Fi')], default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='games',
            name='id',
        ),
        migrations.AddField(
            model_name='games',
            name='info',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.ExtraInfo'),
            preserve_default=False,
        ),
    ]
